"""Initial Reservation Migration

Revision ID: 5d65636f9bd2
Revises: 
Create Date: 2026-02-19 03:50:11.041824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d65636f9bd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('reservation_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED'), nullable=True),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('reservation_seats',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('showtime_id', 'seat_id', name='unique_seat_booking_per_showtime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_seats')
    op.drop_table('reservations')
    # ### end Alembic commands ###
